### ISSUE TITLE
运行你的demo报错了,说什么应用名称不一致

### ISSUE THREAD

**Issue by Mr-Cai** [bravekingzhang/dim#1]
Launching lib\demo\dim_demo\main.dart on Note9 in debug mode...
C:\Users\M\Desktop\Code\flutter_study\android\app\src\debug\AndroidManifest.xml:11:9-38 Error:
	Attribute application@label value=(flutter_study) from AndroidManifest.xml:11:9-38
	is also present at [com.tencent.imsdk:imsdk:4.3.145] AndroidManifest.xml:18:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:9:5-33:19 to override.
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by bravekingzhang** [comment]
`tools:replace="android:label"`加这句到你的Android工程的AndroidManifest中。

**Comment by Mr-Cai** [comment]
> `tools:replace="android:label"`加这句到你的Android工程的AndroidManifest中。
嗯，我之前解决了，还有点登录会失败怎么解决

**Comment by bravekingzhang** [comment]
请看readme，怎么申请自己的appid，和账号。

**Comment by mengsiyitiaojie** [comment]
加了这句话tools:replace="android:label" 还是报错啊

**Comment by mengsiyitiaojie** [comment]
Attribute application@label value=(qiuyin_app) from AndroidManifest.xml:42:9-35
	is also present at [com.tencent.imsdk:imsdk:4.5.45] AndroidManifest.xml:18:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:40:5-112:19 to override.

**Comment by mengsiyitiaojie** [comment]
from AndroidManifest.xml:42:9-35
	is also present at [com.tencent.imsdk:imsdk:4.5.45] AndroidManifest.xml:18:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:40:5-112:19 to override
