### ISSUE TITLE
请问插件里可以实现两个eventChannel的监听吗

### ISSUE THREAD

**Issue by FrankKong** [bravekingzhang/dim#2]
大神请问，FlutterTimPlugin里现在实现了新消息的监听，我这边需要监听会话的刷新，请问怎么加？

**Comment by bravekingzhang** [comment]
这个可以有啊

**Comment by bravekingzhang** [comment]
看了下，印象中记得只能加一个消息通道，所以我简化处理下这个需求为：
如果监听到数据是`[]`表示你该去主动刷新会话列表了，如果监听到的数据不是空数组，说明是会话消息。

**Comment by FrankKong** [comment]
大神有问题哦， java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.EventChannel$EventSink.success(java.lang.Object)' on a null object refere
nce
E/AndroidRuntime(12742):        at com.brzhang.flutter.dim.DimPlugin$2.onRefresh(DimPlugin.java:86)

**Comment by FrankKong** [comment]
一个eventChannel，应该不可以监听两种消息的，查了好久没不知道怎么弄Orz

**Comment by Zhanghaitao1101** [comment]
我也遇到了楼上一样的问题了
