### ISSUE TITLE
集成后安卓  打包报错

### ISSUE THREAD

**Issue by yuefeng007** [bravekingzhang/dim#20]
`* What went wrong:
Execution failed for task ':dim:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\Administrator\.gradle\caches\transforms-2\files-2.1\0a271e99b6771ad4a84318244d532fb7\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     C:\Users\Administrator\.gradle\caches\transforms-2\files-2.1\0a271e99b6771ad4a84318244d532fb7\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      34.2s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin dim...
Running Gradle task 'assembleAarRelease'...
Running Gradle task 'assembleAarRelease'... Done                    1.1s

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'dim'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

The plugin dim could not be built due to the issue above.
`

**Comment by fen666** [comment]
请问上述问题有解决方案了吗？我在打包时也遇到了同样的报错 @yuefeng007

**Comment by yuefeng007** [comment]
> 请问上述问题有解决方案了吗？我在打包时也遇到了同样的报错@ yuefeng007

我三月份开发的时候。dim 功能感觉不太行，作者也不怎么维护
我换了 个比较稳定的 插件  tencent_im_plugin  。还不错。有问题时候，作者回复很及时
