### ISSUE TITLE
dim按照readme文件操作pod update && pod install 报错

### ISSUE THREAD

**Issue by speanut-land** [bravekingzhang/dim#5]
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.3 at /Users/speanut/development/flutter
    • Framework revision b712a172f9 (7 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/speanut/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.3

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • speanut (2) • 925d906d24fc7bfc700785e65ca0a0da59662cd8 • ios • iOS 12.3
    • iPhone 8    • 5824B4F7-8559-4598-A6A5-DE6CDEF331D2     • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator) 

error: Multiple commands produce '/build/ios/Debug-iphonesimulator/dim/dim.framework/Info.plist':
    1) Target 'dim' (project 'Pods') has copy command from '/Users/speanut/development/flutter/.pub-cache/hosted/pub.flutter-io.cn/dim-0.2.6/ios/Classes/MJExtension/Info.plist' to '/build/ios/Debug-iphonesimulator/dim/dim.framework/Info.plist'
    2) Target 'dim' (project 'Pods') has process command with output '/build/ios/Debug-iphonesimulator/dim/dim.framework/Info.plist'
    Runner-cgasymwulsayopauzwnivtcygwgd
    note: Using new build systemnote: Planning buildnote: Constructing build description

**Comment by bravekingzhang** [comment]
https://github.com/flutter/flutter/issues/20685

**Comment by speanut-land** [comment]
> [flutter/flutter#20685](https://github.com/flutter/flutter/issues/20685)

实测有效

**Comment by InTheClodus** [comment]
> [flutter/flutter#20685](https://github.com/flutter/flutter/issues/20685)的確可以
