### ISSUE TITLE
DIM引用到自己项目,AndroidManifest报错

### ISSUE THREAD

**Issue by liaosanshi** [bravekingzhang/dim#6]
D:\yfw-enterprise-flutter\android\app\src\debug\AndroidManifest.xml:18:9-31 Error:
	Attribute application@label value=(孷�����ҵ��) from AndroidManifest.xml:18:9-31
	is also present at [com.tencent.imsdk:imsdk:4.5.15] AndroidManifest.xml:18:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:9:5-19:19 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by mengsiyitiaojie** [comment]
怎么解决

**Comment by bravekingzhang** [comment]
按照 提示  

Suggestion: add 'tools:replace="android:label"' to element at AndroidManifest.xml:9:5-19:19 to override.

**Comment by mengsiyitiaojie** [comment]
有没有聊天的界面可以用
