### ISSUE TITLE
通过获取历史消息记录的api，获取到的消息没有发送时间的字段？

### ISSUE THREAD

**Issue by xb284524239** [bravekingzhang/dim#8]
[{"message":{"longitude":22.539999999999999,"latitude":113.93000000000001,"desc":"腾讯大厦"},"timConversation":{"type":1,"peer":"hoolly1"},"sender":"hoolly3"},{"message":{"longitude":22.539999999999999,"latitude":113.93000000000001,"desc":"腾讯大厦"},"timConversation":{"type":1,"peer":"hoolly1"},"sender":"hoolly3"},{"message":{"text":"haahah"},"timConversation":{"type":1,"peer":"hoolly1"},"sender":"hoolly3"}]

如上消息内容，没有发送时间，接收时间等，那么在消息列表里该如何排序显示呢？

**Comment by bravekingzhang** [comment]
已加

**Comment by bravekingzhang** [comment]
![image](https://user-images.githubusercontent.com/4476322/66814635-84323c00-ef69-11e9-92fa-72fbde65c7fd.png)

**Comment by mengsiyitiaojie** [comment]
我怎么没有呢  [{message: {text: 您好, type: Text}, senderProfile: {allowType: , birthday: 0, customInfo: {}, customInfoUint: {}, faceUrl: , gender: 2, identifier: 1, language: 0, level: 0, location: , nickName: 王长林, role: 0, selfSignature: }, timConversation: {mConversation: {}, peer: 2, type: C2C}}]
